baseURL = 'https://jfdazaluque.github.io/colsara/'
languageCode = 'es'
defaultContentLanguage = "es"
title = "Colegio Sara Deluque Panaflet"

theme = "bootstrap5"

summaryLength = 10

 [frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":fileModTime", ":default"]
    
sectionPagesMenu = "main"
[menu]
    
    [[menu.main]]
    identifier = "el-colegio"
    title = "El Colegio"
    url = "/#/"
    weight = 200
    [[menu.main]]
    parent = "el-colegio"
    identifier = "horizonte-Institucional"
    title = "Horizonte Institucional"
    url = "/el-colegio/horizonte-institucional/presentacion/"
    [[menu.main]]
    parent = "el-colegio"
    identifier = "nuestro-equipo"
    title = "Nuestro Equipo (Docentes)"
    url = "#"
    [[menu.main]]
    parent = "el-colegio"
    identifier = "recorrido-virtual"
    title = "Recorrido Virtual"
    url = "#"
    [[menu.main]]
    parent = "el-colegio"
    identifier = "reconocimientos"
    title = "Reconocimientos"
    url = "#"
    [[menu.main]]
    parent = "el-colegio"
    identifier = "resena-historica"
    title = "Reseña Historica"
    url = "#"
    
    [[menu.main]]
    identifier = "investigacion"
    title = "Investigación"
    url = "/#/" 
    weight = 300
    [[menu.main]]
    parent = "investigacion"
    identifier = "proyectos-pedagogicos"
    title = "Proyectos Pedagógicos"
    url = "/#/"
    [[menu.main]]
    parent = "investigacion"
    identifier = "rincon-literario"
    title = "Rincon Literario"
    url = "/#/"

[[menu.main]]
    identifier = "gpts"
    title = "GPTS"
    url = "/#/"
    weight = 400

    [[menu.main]]
    identifier = "vida-escolar"
    title = "Vida Escolar"
    url = "/#/" 
    weight = 500   
    [[menu.main]]
    parent = "vida-escolar"
    identifier = "circulares"
    title = "Circulares "
    url = "/#/"
    [[menu.main]]
    parent = "vida-escolar"
    identifier = "pqrs "
    title = "PQRS "
    url = "/#/"
    [[menu.main]]
    parent = "vida-escolar"
    identifier = "cuadro-de-honor"
    title = "Cuadro de Honor"
    url = "/#/"
    [[menu.main]]
    parent = "vida-escolar"
    identifier = "aula-virtual "
    title = "Aula Virtual "
    url = "https://colsara.q10.com"
    hrefTargetBlank = true
    

    [[menu.horizonte]]
    identifier = 'presentacion'
    name = 'Presentación'
    url = '../presentacion'
    weight = -190

    [[menu.horizonte]]
    identifier = 'mision'
    name = 'Misión'
    url = '../mision/'
    weight = -180
    
    [[menu.horizonte]]
    identifier = 'vision'
    name = 'Visión'
    title = 'Visión'
    url = '../vision/'
    weight = -170

    [[menu.horizonte]]
    identifier = 'valores'
    name = 'Valores'
    title = 'Valores'
    url = '../avlores/'
    weight = -160

    [[menu.horizonte]]
    identifier = 'politicas-institucionales'
    name = 'Politicas Institucionales'
    title = 'Politicas Institucionales'
    url = '../politicas-institucionales/'
    weight = -150

    [[menu.horizonte]]
    identifier = 'resena-historica'
    name = 'Reseña Historica'
    title = 'Reseña Historica'
    url = '../resena-historica/'
    weight = -140
    

    